spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/board
        username: board_sys
        password: 12345
    jpa:
        hibernate:
            ddl-auto: update
            jdbc:
                time_zone: Asia/Seoul
        show-sql: true

server:
    port: 8082
    address: 0.0.0.0

logging:
    level:
        root: info
